version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: caselog_db_pro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - caselog_net

  backend:
    build: ./backend
    container_name: caselog_backend_pro
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: $MYSQL_USER
      DB_PASS: $MYSQL_PASSWORD
      DB_NAME: $MYSQL_DATABASE
    networks:
      - caselog_net

  nginx:
    image: nginx:alpine
    container_name: caselog_nginx_pro
    restart: always
    ports:
      - "$WEB_PORT:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - caselog_net

volumes:
  db_data:

networks:
  caselog_net:
    driver: bridge
